version = 0.1

[prod.deploy.parameters]
stack_name = "optisoftware-prod-contact-form"
resolve_s3 = true
s3_prefix = "optisoftware-prod-contact-form"
region = "us-east-1"
profile = "prod-sso"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
fail_on_empty_changeset = false
